### ISSUE TITLE
I cannot able to build the project

### ISSUE THREAD

**Issue by Sethuraji** [thomasjungblut/thomasjungblut-common#1]
Hello Sir,
        I used the netbeans IDE to deploy the given project ,but I got the error
 
"Failed to execute goal on project thomasjungblut-common: Could not resolve dependencies for project de.jungblut.common:thomasjungblut-common:jar:1.0: Could not find artifact de.jungblut.math:tjungblut-math:jar:1.2-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException"  

What can I do further to build the project..Do I need to change the POM.xml file ,if so what to change ,Sir.Waiting for the earliest response.

Thanks in Early.

**Comment by thomasjungblut** [comment]
just install:
https://github.com/thomasjungblut/tjungblut-math

**Comment by Sethuraji** [comment]
Thank you for your earliest response Sir.But I don't get what you are trying to say with "install",I have downloaded the "tjungblut-math-master.zip" file and I tried to import this file with that project.By doing that too,I cannot able to resolve those same issues.Could you please help me to find a way to deploy the given project,Sir.

Thank in Early.

**Comment by thomasjungblut** [comment]
Please follow the instructions in the other project. Install means:
`mvn clean package install -Dgpg.skip=true -DskipTests`

**Comment by Sethuraji** [comment]
Thank you, Sir. You helped me a lot. But I have a doubt in the Minhashtest.java file, It compares only double vector (data structure ), how to use it when comparing the Strings ?.

**Comment by thomasjungblut** [comment]
what strings?

**Comment by Sethuraji** [comment]
Sir, I want to use my text document as a source to the program and find it's minhash signatures. Could you please help me in that? 

Thanks in advance

**Comment by thomasjungblut** [comment]
You need to vectorize your text into vectors.

**Comment by Sethuraji** [comment]
Sir, 
   Thank you, I have already created the program to read the files and store it in a Set Array. Is it possible to convert the Set to Vector, if so how?. 

Thanks in advance.

**Comment by thomasjungblut** [comment]
Have a look here:

http://stackoverflow.com/questions/28536678/run-perceptron-algorithm-on-a-hash-map-feature-vecteur-java/28540733#28540733

I have some classes in this repo that actually do those things. Take a look at:

https://github.com/thomasjungblut/thomasjungblut-common/blob/master/src/de/jungblut/nlp/TokenizerUtils.java

https://github.com/thomasjungblut/thomasjungblut-common/blob/master/src/de/jungblut/nlp/BigramTokenizer.java

https://github.com/thomasjungblut/thomasjungblut-common/blob/master/src/de/jungblut/nlp/VectorizerUtils.java

**Comment by thomasjungblut** [comment]
In case you need more hand-holding, I've written and end-to-end blog post about it:

http://codingwiththomas.blogspot.co.uk/2015/03/minhashing-for-beginners.html

Hope it helps!
Thomas

**Comment by Sethuraji** [comment]
It solved my issues, you have helped me a lot, Thank you very much, Sir.
