### ISSUE TITLE
How to get the number of Data points in each cluster of Mean Shift clustering ?

### ISSUE THREAD

**Issue by gaperon** [thomasjungblut/thomasjungblut-common#2]
Hello,
I use the MeanShiftClustering class to put into clusters data points (gps coordinates) and i cant get the number of points in each of DoubleVector. Is it possible to get it ?

**Comment by thomasjungblut** [comment]
It's possible yes, but not implemented. You can simply loop over your data points and measure the euclidian distance to the centers.
You can basically take the loop from that line:
